### ISSUE TITLE
pycurl is not installed, detectip will not work without it

### ISSUE THREAD

**Issue by purplesrl** [lucagiove/luchizz#14]
[ root@docker: ~ ]# detectip
Traceback (most recent call last):
  File "/usr/local/bin/detectip", line 34, in <module>
    import pycurl
ImportError: No module named pycurl

pip install pycurl is not working also:

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-RE67lQ/pycurl/

Only workaround is:

apt-get install python-pycurl

**Comment by lucagiove** [comment]
added to base with the pullreq 16
in the future detectip will be rewritten in sh sice python is overkill and slow
