### ISSUE TITLE
set_fqdn file /etc/hosts is not modified

### ISSUE THREAD

**Issue by Dark-Vex** [lucagiove/luchizz#6]
This function:
    sed('/etc/hosts', '127\.0\.1\.1.*',
        '127\.0\.1\.1\t{}\t{}'.format(fqdn, hostname),
        use_sudo=True)

does not work if inside the file /etc/hosts is not present 127.0.1.1

**Comment by lucagiove** [comment]
Now it checks if 127.0.1.1 is in hosts file otherwise will append it and then sed on it, fixed in 60ee01b
